# Data Visualization in Python: Basic Data Visualization

## Histograms and Bar Charts

### Histograms

*Histograms* refer to graphical representations that display data by way of bars to show the frequency of numerical data.

### Bar Charts

*Bar charts* refer to pictorial representations that use bars to compare different categories of data.

From a programming perspective, there isn't much of difference between visualizing a histogram and bar chart.  Because of this both are implemented the same way using toyplot, which is using the **bars** mark.

In [1]:
import numpy
import toyplot

In [12]:
data = numpy.random.randint(0, 10, (10,10))
hist = numpy.histogram(data)
print()
print("The raw data is:")
print()
print(data)
print()
print("The histogram for the data is:")
canvas = toyplot.Canvas(500,500)
axes = canvas.cartesian()
mark = axes.bars(hist)
print()
print("The (stacked) bar chart of the data is:")
print()
canvas = toyplot.Canvas(500,500)
axes = canvas.cartesian()
mark = axes.bars(data)


The raw data is:

[[6 9 9 1 2 0 6 6 9 8]
 [1 4 1 5 8 9 2 5 8 2]
 [3 7 3 0 3 3 2 4 1 0]
 [0 9 5 2 5 4 0 3 0 9]
 [8 3 5 5 8 1 9 3 5 6]
 [1 9 3 8 0 6 3 7 3 5]
 [9 6 8 5 6 1 1 9 4 3]
 [6 3 6 0 6 7 4 3 1 2]
 [4 4 2 0 9 6 6 2 5 1]
 [7 6 1 3 8 8 3 4 2 9]]

The histogram for the data is:

The (stacked) bar chart of the data is:



<svg class="toyplot-canvas-Canvas" height="500.0px" id="t5008488790af49b3b75a8c32c075d7ab" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 500.0 500.0" width="500.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> 0 3 6 9 0 5 10 15

<svg class="toyplot-canvas-Canvas" height="500.0px" id="t4ec82cd6eeea423db740138bd759c1f3" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 500.0 500.0" width="500.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> 0 5 10 0 20 40 60

## Line Charts

*Line charts* are charts that display information as a series of data points connected by a straight line.  They are generated in toyplot using the **plot** mark.

In [18]:
x = numpy.arange(0, 10)
y = x**2
canvas = toyplot.Canvas(1000, 500)
axes = canvas.cartesian()
mark = axes.plot(x,y)

<svg class="toyplot-canvas-Canvas" height="500.0px" id="tfe5172fbe52246fcad03932798adcf30" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 1000.0 500.0" width="1000.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> 0 3 6 9 0 25 50 75

## Scatter Plots

*Scatter plots* are mathematical diagrams the using Cartesian coordinates to display values for two variables for a set of data.  Though scatter plots typically only show data for 2 variables, there are ways to increase the number of variables displayed by adding an additional axis, using colors, marker size, marker symbol, etc.  They are generated in toyplot using the **scatterplot** mark.

In [16]:
data = numpy.random.randint(0, 10, (10,2))

canvas = toyplot.Canvas(1000, 500)
axes = canvas.cartesian()
mark = axes.scatterplot(data[:,0], data[:,1], size=10)

<svg class="toyplot-canvas-Canvas" height="500.0px" id="t15cb095820ed452f961cf2ad3cdb5cb7" preserveAspectRatio="xMidYMid meet" style="background-color:transparent;border-color:#292724;border-style:none;border-width:1.0;fill:rgb(16.1%,15.3%,14.1%);fill-opacity:1.0;font-family:Helvetica;font-size:12px;opacity:1.0;stroke:rgb(16.1%,15.3%,14.1%);stroke-opacity:1.0;stroke-width:1.0" viewBox="0 0 1000.0 500.0" width="1000.0px" xmlns="http://www.w3.org/2000/svg" xmlns:toyplot="http://www.sandia.gov/toyplot" xmlns:xlink="http://www.w3.org/1999/xlink"> 0 2 5 8 0 2 5 8